/**
 * Build the Counter-Strike 2 catalog: every weapon CASE (a set) and the skins
 * it can drop (cards), from the free, community-maintained bymykel/CSGO-API.
 *
 * Structure maps cleanly onto the existing schema:
 *   - a Case                 -> a `sets` row (game counter-strike-2, language EN)
 *   - each skin in `contains`-> a `cards` row, rarity = its blue/purple/pink/red grade
 *   - each `contains_rare`   -> a `cards` row, rarity = rare_special (knives/gloves, gold)
 *
 * DELIBERATELY price-less: skin prices come from Skinport (a separate adapter),
 * so cards land here searchable + imaged but unvalued until that runs. The odds
 * are the same official five tiers for every case — those live in
 * data/pullrates/counter-strike-2/ (generated by build-cs2-odds.ts). Idempotent.
 *
 *   npx tsx --env-file=.env.local scripts/build-cs2-catalog.ts
 */
import { eq, sql } from "drizzle-orm";

import { cards, games, getDb, sets } from "@/lib/db";

const CRATES_URL =
  "https://raw.githubusercontent.com/ByMykel/CSGO-API/main/public/api/en/crates.json";

/** bymykel grade name -> our CS2 rarity vocab. contains_rare is always gold. */
const GRADE_MAP: Record<string, string> = {
  "Mil-Spec Grade": "mil_spec",
  Restricted: "restricted",
  Classified: "classified",
  Covert: "covert",
};

interface CrateItem {
  id: string;
  name: string;
  image?: string | null;
  rarity?: { id?: string; name?: string } | null;
}
interface Crate {
  id: string;
  name: string;
  type?: string;
  image?: string | null;
  contains?: CrateItem[];
  contains_rare?: CrateItem[];
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

async function main() {
  const db = getDb();
  const [game] = await db.select().from(games).where(eq(games.slug, "counter-strike-2"));
  if (!game) throw new Error("counter-strike-2 game not seeded — run scripts/seed.ts first");

  console.log("Fetching bymykel crates…");
  const res = await fetch(CRATES_URL);
  if (!res.ok) throw new Error(`crates.json ${res.status}`);
  const all = (await res.json()) as Crate[];
  const casesList = all.filter((c) => c.type === "Case");
  console.log(`${casesList.length} weapon cases.`);

  let setsDone = 0;
  let cardsStored = 0;

  for (const crate of casesList) {
    const code = slugify(crate.name);
    const [setRow] = await db
      .insert(sets)
      .values({
        gameId: game.id,
        code,
        name: crate.name,
        language: "EN",
        logoUrl: crate.image ?? null,
        externalIds: { bymykel: crate.id },
      })
      .onConflictDoUpdate({
        target: [sets.gameId, sets.code, sets.language],
        set: { name: crate.name, logoUrl: crate.image ?? null, updatedAt: new Date() },
      })
      .returning({ id: sets.id });

    const rows: { rarity: string; item: CrateItem }[] = [
      ...(crate.contains ?? []).map((item) => ({
        rarity: GRADE_MAP[item.rarity?.name ?? ""] ?? null,
        item,
      })),
      // Knives + gloves — bymykel labels them Covert, but they are the gold
      // Rare Special Item tier, a different drop pool entirely.
      ...(crate.contains_rare ?? []).map((item) => ({ rarity: "rare_special", item })),
    ].filter((r): r is { rarity: string; item: CrateItem } => r.rarity !== null);

    // Dedup by skin id (a skin lists once per case) and bulk-upsert.
    const byId = new Map<string, { rarity: string; item: CrateItem }>();
    for (const r of rows) byId.set(r.item.id, r);
    const values = [...byId.values()].map(({ rarity, item }) => ({
      setId: setRow!.id,
      name: item.name,
      number: item.id, // skins have no collector number; the bymykel id is the stable key
      rarity,
      treatment: "base",
      imageUrl: item.image ?? null,
      // Store the base market_hash_name so the Skinport adapter can build the
      // per-wear names (…(Field-Tested) etc.) when pricing lands.
      externalIds: { bymykel: item.id, market_hash_name: item.name },
    }));

    const CHUNK = 500;
    for (let i = 0; i < values.length; i += CHUNK) {
      await db
        .insert(cards)
        .values(values.slice(i, i + CHUNK))
        .onConflictDoUpdate({
          target: [cards.setId, cards.number, cards.treatment],
          set: {
            name: sql`excluded.name`,
            rarity: sql`excluded.rarity`,
            imageUrl: sql`excluded.image_url`,
            externalIds: sql`${cards.externalIds} || excluded.external_ids`,
            updatedAt: new Date(),
          },
        });
    }
    cardsStored += values.length;
    setsDone++;
    if (setsDone % 10 === 0) console.log(`  [${setsDone}/${casesList.length}] ${crate.name}`);
  }

  console.log(`\nDone: ${setsDone} cases, ${cardsStored} skins stored (no prices — Skinport wires them later).`);
}

main()
  .then(() => process.exit(0))
  .catch((e: unknown) => {
    console.error("build-cs2-catalog failed:", e instanceof Error ? e.message : e);
    process.exit(1);
  });
